services:
  web:
    image: php:8.2-apache
    container_name: arq_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: arq_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_DATABASE: db_arqueologia
      MYSQL_USER: user_arq
      MYSQL_PASSWORD: pass_arq_123
    ports:
      - "3306:3306"
    volumes:
      - arq_db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  arq_db_data:
